version: "3"
services: 
    mariadb:
        image: mariadb:10.5
        platform: linux/amd64
        container_name: mariadb
        networks: 
            - docker
        ports:
            - 3306:3306
        volumes: 
            - ${PWD}/database:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: 1234
            MARIADB_DATABASE: docker_lab

    django:
        build: .
        container_name: django
        command:
            - bash
            - -c
            - |
              python manage.py migrate
              gunicorn --bind 0:8000 config.wsgi:application
        networks: 
            - docker
        ports: 
            - 8000:8000
        volumes: 
            - ${PWD}:/home/django
        depends_on: 
            - mariadb
        expose:
            - 8000
        restart: always

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./staticfiles/:/static
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/certs/:/etc/nginx/certs/
            - ./nginx/certs/django.crt:/etc/nginx/certs/django.crt
        networks:
            - docker
        depends_on:
            - django

networks: 
    docker:
        